#!/bin/sh

src="$PWD"
dst=~/.local/bin

install_user_scripts() {
  mkdir -p "$dst"
  for i in dmenu_bind dwm-start dwm-xprop; do
    cp -fv "$src"/bin/"$i" "$dst"
    chmod 700 "$dst"/"$i"
  done
} 

install_suckless_packages() {
  for i in st dwm slstatus; do # order matters
    cd "$src"/"$i" || exit
    makepkg -fsic --needed --noconfirm
  done
}

main() {
  install_user_scripts
  install_suckless_packages
}

main "$@"
