#!/usr/bin/env bash

src=~/projects/suckless

install_user_scripts() {
  local dst=~/.local/bin
  mkdir -p "$dst"
  for file in "$src"/_scripts/*; do
    cp -fv "$file" "$dst"
  done
  chmod 700 "$dst"/*
} 

install_suckless_packages() {
  local pkg=(st dwm slstatus) # order matters
  for i in "${pkg[@]}"; do
    cd "$src"/"$i" || exit
    makepkg -fsic --needed --noconfirm
  done
}

main() {
  install_user_scripts
  install_suckless_packages
}

main "$@"
